AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with cfn-response.
Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import json
          import boto3
          def lambda_handler(event, context):
              # TODO implement
              ssm = boto3.client('ssm')
              username = ssm.get_parameter(Name='username')['Parameter']['Name']
              value = ssm.get_parameter(Name='username')['Parameter']['Value']
              print(ssm.get_parameter(Name='username'))
              print(username)
              print(value)

              string = "Name = " + username + '\n' + "value = " + value
              encoded_string = string.encode("utf-8")

              bucket_name = "sashanktestbucket"
              file_name = "ssm_parameters.txt"
              s3_path = file_name

              s3 = boto3.resource("s3")
              s3.Bucket(bucket_name).put_object(Key=s3_path, Body=encoded_string)

              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
      Description: Create a lambda function to fetch ssm parameters
      FunctionName: fetch_ssm_param1
      Handler: index.lambda_handler
      Role: arn:aws:iam::397878346871:role/AWSLambdaS3Cloud
      Runtime: python3.6
      Timeout: 300